template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "nort2938"
__REPO__ = "lang-hdn"
__UND2C__ = "hdn"
__UNDEFINED__ = "Northern Haida"
__UND__ = "hdn"
