template = "https://github.com/giellalt/template-lang-und"
rev_id = 274
template_sha = "43a0f0c0afaa856365e2bf3d3cb7eae06d27cc4d"

[replacements]
__GLOTTOLOG_ID__ = "nort2938"
__REPO__ = "lang-hdn"
__UND2C__ = "hdn"
__UNDEFINED__ = "Northern Haida"
__UND__ = "hdn"
